repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: "4807a245eaf50df28f31ab688533e443f136222f"
    hooks:
      - id: stylua-github

  - repo: https://github.com/lunarmodules/luacheck
    rev: "81e0835cf5b54b9cb2101b21edeec011dec5fff3"
    hooks:
      - id: luacheck

  - repo: https://github.com/golangci/golangci-lint
    rev: "v1.43.0"
    hooks:
      - id: golangci-lint
